### ISSUE TITLE
Published npm package is missing `dist/options/index.d.ts`

### ISSUE THREAD

**Issue by intagaming** [Lightrix/files-pipe#22]
The published npm package is missing `dist/options/index.d.ts`. See: https://www.npmjs.com/package/files-pipe?activeTab=code

This missing file causes the Astro LSP to complain (`files-pipe` were used in `astro-compress`):

<details><summary>~/.local/state/nvim/lsp.log</summary>

```
[ERROR][2023-06-04 14:51:33] .../vim/lsp/rpc.lua:734    "rpc"   "/home/an7/.local/share/nvim/mason/bin/astro-ls"        "stderr"        "node:fs:1615\n  handl
eErrorFromBinding(ctx);\n  ^\n\nError: ENOTDIR: not a directory, stat '/home/an7/files/dev/coccoc-astro/node_modules/.pnpm/astro-compress@1.1.46/node_modules/
files-pipe/dist/options/index.js/dist'\n    at Object.statSync (node:fs:1615:3)\n    at Object.stat (/home/an7/.local/share/nvim/mason/packages/astro-language
-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/out/node/index.js:67:38)\n    at Object.stat (/home/an7/.local/share/nvim/ma
son/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-server/out/common/server.js:185:43)\n    at Proxy.direct
oryExists (/home/an7/.local/share/nvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/typescript/out/sys.js:12
1:27)\n    at directoryProbablyExists (/home/an7/files/dev/coccoc-astro/node_modules/.pnpm/typescript@5.1.3/node_modules/typescript/lib/typescript.js:17308:42
)\n    at Object.directoryExists (/home/an7/files/dev/coccoc-astro/node_modules/.pnpm/typescript@5.1.3/node_modules/typescript/lib/typescript.js:139767:18)\n 
   at host.directoryExists (/home/an7/files/dev/coccoc-astro/node_modules/.pnpm/typescript@5.1.3/node_modules/typescript/lib/typescript.js:116065:50)\n    at 
host.compilerHost.directoryExists (/home/an7/files/dev/coccoc-astro/node_modules/.pnpm/typescript@5.1.3/node_modules/typescript/lib/typescript.js:119524:37)\n
    at directoryProbablyExists (/home/an7/files/dev/coccoc-astro/node_modules/.pnpm/typescript@5.1.3/node_modules/typescript/lib/typescript.js:17308:42)\n    
at loadNodeModuleFromDirectoryWorker (/home/an7/files/dev/coccoc-astro/node_modules/.pnpm/typescript@5.1.3/node_modules/typescript/lib/typescript.js:40408:61)
 {\n  errno: -20,\n  syscall: 'stat',\n  code: 'ENOTDIR',\n  path: '/home/an7/files/dev/coccoc-astro/node_modules/.pnpm/astro-compress@1.1.46/node_modules/fil
es-pipe/dist/options/index.js/dist'\n}\n\nNode.js v18.15.0\n"
```

</details> 

Can you please packing up a new patch version with that file included and publish it, and also update `astro-compress` to use the new patch version?

**Comment by NikolaRHristov** [comment]
Yeah, somehow that exact file does not get compiled on GitHub CI or any Debian based. I will update shortly.

**Comment by NikolaRHristov** [comment]
Fixed in https://github.com/Lightrix/files-pipe/releases/tag/v0.0.7 and https://github.com/astro-community/astro-compress/releases/tag/v1.1.47

**Comment by intagaming** [comment]
Tested it just now, works flawlessly! Thanks for your speedy response!

**Comment by NikolaRHristov** [comment]
🤙🏻
